### PR TITLE
Fixed partner name crasher for artworks in grid

### LINKED ISSUE #182: Fix RCTFatalException in RCTFatal, line 133
@artsyit commented on [Thu Jun 16 2016](https://github.com/artsy/eigen/issues/1723)

### Stacktrace ###

<pre>-;RCTFatal;RCTAssert.m;133
RCTExceptionsManager;reportFatalException:stack:exceptionId:;RCTExceptionsManager.m;64
RCTModuleMethod;invokeWithBridge:module:arguments:;RCTModuleMethod.m;489
RCTBatchedBridge;_handleRequestNumber:moduleID:methodID:params:;RCTBatchedBridge.m;977
RCTBatchedBridge;handleBuffer:;RCTBatchedBridge.m;905</pre>

### Reason ###

*** Terminating app due to uncaught exception 'RCTFatalException: Unhandled JS Exception: null is not an object (evaluating 'this.props.artwork.partner.name')', reason: 'Unhandled JS Exception: null is not an object (evaluating 'this.props.artwo..., stack:
value@672:1216
_renderValidatedComponentWithoutOwnerOrContext@385:6723
_renderValidatedComponent@385:6851
performInitialMount@385:2701
mountComponent@385:1750
mountComponent@376:181
_mountChildAtIndex@380:2434
_updateChildren@380:1948
updateChildren@380:1590
receiveComponent@361:827
receiveComponent@376:579
updateChildren@383:414
_reconcilerUpdateChildren@380:969
_updateChildren@380:1697
updateChildren@380:1590
receiveComponent@361:827
receiveComponent@376:579
updateChildren@383:414
_reconcilerUpdateChildren@380:969
_updateChildren@380:1697
updateChildren@380:1590
receiveComponent@361:827
receiveComponent@376:579
updateChildren@383:414
_reconcilerUpdateChildren@380:969
_updateChildren@380:1697
updateChildren@380:1590
receiveComponent@361:827
receiveComponent@376:579
_updateRenderedComponent@385:6215
_performComponentUpdate@385:5984
updateComponent@385:5261
receiveComponent@385:4477
receiveComponent@376:579
_updateRenderedComponent@385:6215
_performComponentUpdate@385:5984
updateComponent@385:5261
performUpdateIfNecessary@385:4693
performUpdateIfNecessary@376:854
l@373:749
perform@379:495
perform@379:495
perform@373:1811
B@373:1983
closeAll@379:1132
perform@379:582
batchedUpdates@450:457
a@373:317
_receiveRootNodeIDEvent@363:813
receiveEvent@363:923
value@286:3191
<unknown>@286:1431
y@286:618
value@286:1403
'

### Link to HockeyApp ###

* [https://rink.hockeyapp.net/manage/apps/37029/crash_reasons/125182864](https://rink.hockeyapp.net/manage/apps/37029/crash_reasons/125182864)

### PR DESCRIPTION
**Pull request by sarahscott**
This artwork doesn't have a partner associated with it, and was crashing upon load (I added a null check inside the view to check; before it wouldn't render anything before the crash):

simulator screen shot jun 20 2016 3 59 20 pm

Now it only renders a `SerifText` view for the partner name if the partner exists:

simulator screen shot jun 20 2016 4 13 47 pm

Fixes #182 

Pending https://github.com/artsy/eigen/issues/1732

### CODE REVIEW

**Comment by alloy** [comment]
This looks good 👍 

However, can you also find the ID/slug of the offending artwork and with that info check with the responsible people if it’s valid for a ‘for sale’ artwork to not have a partner?

**Comment by sarahscott** [comment]
Yeah I just checked and I think there's something wrong with this work: https://www.artsy.net/artwork/barry-mcgee-untitled-geometric

**Comment by alloy** [comment]
I wonder, this fixes the crash when trying to display the artworks on the Artist view, but can you select the artwork and view it without e.g. the Artwork view crashing?

**Comment by sarahscott** [comment]
For nice github record-keeping purposes: no, artwork view will not crash, but will show an incomplete view controller.

**Comment by alloy** [comment]
Can you revert 3023232574c7c578e67580d0b4d9bf8febf38e51? As it turns out that works without a partner are expected to exist in certain cases.

File: lib/components/artist/artworks/grid.js [hunk 1]
```diff
@@ -118,7 +118,7 @@ class ArtworksGrid extends React.Component {
       // There are artworks without images and other ‘issues’. Like Force we’re just going to reject those for now.
       // See: https://github.com/artsy/eigen/issues/1667
       //
-      if (artwork.image) {
+      if (artwork.image && artwork.partner) {
```
Comment (sarahscott) [inline lib/components/artist/artworks/grid.js]: Should I leave this here until we figure out what (if anything) needs to be changed on the Artwork page?

Comment (alloy) [inline lib/components/artist/artworks/grid.js]: No let's show the artwork but remove the label, as per your earlier commit. We'll deal with the artwork separately later. It's an edge case anyways.

**Comment by alloy** [comment]
Alright, merging!
