### PR TITLE
[Artist] Fix link to auction results.

### LINKED ISSUE #392: Auction results send users to old artist page
tap auction results, get sent to old page. we should send users directly to the auction results MG view.

### PR DESCRIPTION
**Pull request by alloy**
Fixes #392.

### CODE REVIEW

File: lib/components/artist/about.js [hunk 1]
```diff
@@ -39,7 +39,7 @@ class About extends React.Component {
     if (this.props.artist.is_display_auction_link) {
       // Keeps the same margins as the bio text
       const sideMargin = Dimensions.get('window').width > 700 ? 50 : 20
-      const url = `/artist/${this.props.artist.id}/auctions-results`
+      const url = `/artist/${this.props.artist.id}/auction-results`
```
Comment (mennenia) [inline lib/components/artist/about.js]: that `s` 😭
