### PR TITLE
Fixes display of artworks in non-expanding grids in artwork rails

### LINKED ISSUE #528: Empty live bids rail
Looks related to https://github.com/artsy/emission/pull/469 maybe?

simulator screen shot may 10 2017 1 37 26 pm

### PR DESCRIPTION
**Pull request by ashfurrow**
A repeat of https://github.com/artsy/emission/pull/469 which was merged into a 1.2.3 release (that was never merged into master). Fixes #528. Skip New Tests.

### CODE REVIEW

**Comment by ArtsyOpenSource** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>Missing Test Files:

- `src/lib/components/home/artwork_rails/__tests__/artwork_rail-tests.tsx`

If these files are supposed to not exist, please update your PR body to include "Skip New Tests".</td>
    </tr>
  </tbody>
</table>


<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>Could not find stories using these components:

- `ArtworkRail`

</td>
    </tr>
  </tbody>
</table>



<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

File: src/lib/components/home/artwork_rails/artwork_rail.tsx [hunk 1]
```diff
@@ -122,7 +122,10 @@ class ArtworkRail extends React.Component<Props & RelayPropsWorkaround, State> {
   }
 
   onGridLayout(event) {
-    this.setState({ gridHeight: event.nativeEvent.layout.height })
+    let { height } = event.nativeEvent.layout
```
Comment (alloy) [inline src/lib/components/home/artwork_rails/artwork_rail.tsx]: Preferably use `const` over `let`. Not a blocker.
