### PR TITLE
[Artworks] Use unique artwork component keys. #tiny

### LINKED ISSUE #289: [Home][ArtworkRail] Images after pull-to-refresh don't scale correctly
correct scaling (after initial render):

simulator screen shot sep 13 2016 2 33 49 pm

incorrect scaling (after content is refreshed):

simulator screen shot sep 13 2016 2 32 52 pm

### PR DESCRIPTION
**Pull request by alloy**
Otherwise a component for a different artwork (with a different image
aspect ratio) might get re-used for the wrong artwork, leading to
incorrectly scaled images.

Fixes #289.

### CODE REVIEW

File: lib/components/artwork_grids/generic_grid.js [hunk 1]
```diff
@@ -80,7 +80,8 @@ class GenericArtworksGrid extends React.Component {
       const artworkComponents = []
       const artworks = sectionedArtworks[i]
       for (let j = 0; j < artworks.length; j++) {
-        artworkComponents.push(<Artwork artwork={artworks[j]} key={'artwork-' + j} />)
```
Comment (alloy) [inline lib/components/artwork_grids/generic_grid.js]: This is why we really shouldn’t ever be generating keys like this, but use unique identifiers instead.

**Comment by ArtsyOpenSource** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="true">No CHANGELOG added.</td>
    </tr>
  </tbody>
</table>
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="true">The following files do not have tests: <a href="https://github.com/artsy/emission/blob/180362cbaca988d13118d181c6409719f21bc8d0/lib/components/artwork_grids/generic_grid.js">lib/components/artwork_grids/generic_grid.js</a></td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">danger</a>
</p>

**Comment by sarahscott** [comment]
Sweet
