### PR TITLE
Fixed inverted button width in artworks header and disappearance in artist cards #tiny

### LINKED ISSUE #257: [Home][ArtistRail] Follow button disappears on iPad
simulator screen shot aug 26 2016 1 46 18 pm

### PR DESCRIPTION
**Pull request by sarahscott**
I've updated the `inverted_button` component to be more malleable since it's used in many different places.

It shows up on both iPhone & iPad now:

simulator screen shot oct 4 2016 3 44 54 pm

And it doesn't look weird on iPad anymore:

simulator screen shot oct 4 2016 3 43 36 pm

Fixes #257 & #285 

Also makes artist view controller more in line with its original spec: https://github.com/artsy/eigen/issues/1132

### CODE REVIEW

File: lib/components/artist/header.js [hunk 1]
```diff
@@ -147,6 +149,10 @@ const styles = StyleSheet.create({
   },
   followButton: {
     height: 40,
+    width: isPad ? 330 : null,
```
Comment (sarahscott) [inline lib/components/artist/header.js]: I can't use `isPad && 330` here because styles cannot be booleans.

File: lib/components/buttons/inverted_button.js [hunk 2]
```diff
@@ -79,8 +77,6 @@ const styles = StyleSheet.create({
     flex: 1,
     justifyContent: 'center',
     alignItems: 'center',
-    marginLeft: sideMargin,
```
Comment (sarahscott) [inline lib/components/buttons/inverted_button.js]: This makes it such that the button styles its own contents but not its overall width, height, or margins.

**Comment by ArtsyOpenSource** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="true">No CHANGELOG added.</td>
    </tr>
  </tbody>
</table>
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="true">The following files do not have tests: <a href="https://github.com/artsy/emission/blob/6214a70a0aeb1aeae4ec1ddb9e6502d83405ebd0/lib/components/artist/header.js">lib/components/artist/header.js</a>, <a href="https://github.com/artsy/emission/blob/6214a70a0aeb1aeae4ec1ddb9e6502d83405ebd0/lib/components/buttons/inverted_button.js">lib/components/buttons/inverted_button.js</a>, <a href="https://github.com/artsy/emission/blob/6214a70a0aeb1aeae4ec1ddb9e6502d83405ebd0/lib/components/home/artwork_rails/artwork_rail_header.js">lib/components/home/artwork_rails/artwork_rail_header.js</a>, <a href="https://github.com/artsy/emission/blob/6214a70a0aeb1aeae4ec1ddb9e6502d83405ebd0/lib/components/tab_view.js">lib/components/tab_view.js</a> &amp; <a href="https://github.com/artsy/emission/blob/6214a70a0aeb1aeae4ec1ddb9e6502d83405ebd0/lib/containers/artist.js">lib/containers/artist.js</a></td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">danger</a>
</p>

File: lib/components/artist/header.js (hunk 1 above)
Comment (mennenia) [inline lib/components/artist/header.js]: so how come the width would be null if it's on a phone? :o

File: lib/components/buttons/inverted_button.js (hunk 2 above)
Comment (mennenia) [inline lib/components/buttons/inverted_button.js]: 👍

File: lib/components/artist/header.js (hunk 1 above)
Comment (sarahscott) [inline lib/components/artist/header.js]: It's unspecified because it expands to fit with its margins.

Comment (mennenia) [inline lib/components/artist/header.js]: cool!

**Comment by mennenia** [comment]
🎉 merginggg
