### PR TITLE
[Show] Guard against missing image

### LINKED ISSUE #139: [Shows] Crash when no meta_image is available
This show has none https://www.artsy.net/show/serpentine-galleries-alex-katz. Looking at the shows for Alex Katz on Force doesn’t seem to reveal this show at all: https://www.artsy.net/artist/alex-katz/shows.

So either Force is not showing shows where the `meta_image` is missing or they are filtering out this show based on another flag that I have not been able to figure out, based on [the data in metaphysics](https://metaphysics-production.artsy.net/?query=%7B%0A%09partner_show(id%3A%20%22serpentine-galleries-alex-katz%22)%20%7B%0A%20%20%20%20id%0A%20%20%20%20name%0A%20%20%20%20description%0A%20%20%20%20is_fair_booth%0A%20%20%20%20status%0A%20%20%20%20images(size%3A%201)%20%7B%0A%20%20%20%20%20%20url%0A%20%20%20%20%7D%0A%20%20%20%20meta_image%20%7B%0A%20%20%20%20%20%20href%0A%20%20%20%20%7D%0A%20%20%20%20cover_image%20%7B%0A%20%20%20%20%20%20href%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D) at least.

We shouldn’t even crash, but I would like to know if this is simply a problem with the show metadata that needs to be fixed or that we need to be doing something differently.

### PR DESCRIPTION
**Pull request by alloy**
Fixes #139

### CODE REVIEW

File: lib/components/artist/shows/small_image_show.js [hunk 1]
```diff
@@ -16,10 +16,12 @@ class SmallImageShow extends React.Component {
...
+    const image = show.meta_image;
+    const imageURL = image && image.cropped.url;
     return (
       <TouchableWithoutFeedback onPress={this.handleTap.bind(this)} >
         <View style={styles.container}>
-          <OpaqueImageView imageURL={show.meta_image.cropped.url} style={styles.image} />
+          <OpaqueImageView imageURL={imageURL} style={styles.image} />
           <ShowMetadata show={show} />
         </View>
       </TouchableWithoutFeedback>
```
Comment (alloy) [inline lib/components/artist/shows/small_image_show.js]: @sarahscott These three components are all the same in terms of the components they use and their JSX code, the only difference is styling. I think that can be refactored so that only the styling needs to be specified for each individual variant, but the JSX can stay the same and in 1 source file.

File: lib/components/artist/shows/large_image_show.js [hunk 2]
```diff
@@ -22,11 +22,14 @@ class LargeImageShow extends React.Component {
   }
 
   render() {
+    const show = this.props.show;
+    const image = show.meta_image;
+    const imageURL = image && image.cropped.url;
```
Comment (alloy) [inline lib/components/artist/shows/large_image_show.js]: @sarahscott @mennenia Another way to deal with null-ing, this is similar to `foo ?: fallback` in C, but that shorthand of the ternary. See https://repl.it/CWx3

File: Example/Emission/AppDelegate.m [hunk 3]
```diff
@@ -10,6 +10,8 @@
 #import <React/RCTUtils.h>
 #import <TargetConditionals.h>
 
+#define ARTIST @"banksy"
```
Comment (orta) [inline Example/Emission/AppDelegate.m]: SHOUTY

Comment (alloy) [inline Example/Emission/AppDelegate.m]: Hey, it stood out, didn’t it? ;)

File: lib/components/artist/shows/large_image_show.js (hunk 2 above)
Comment (mennenia) [inline lib/components/artist/shows/large_image_show.js]: 💥
