### PR TITLE
[Related Artists] Fix left margin of grid view

### LINKED ISSUE #131: [Related Artists] Grid not centered
Reported by @sarahscott.

image_0-6

### PR DESCRIPTION
**Pull request by mennenia**
Fix #131 

cc @katarinabatina, this is what I went with:

screen shot 2016-05-31 at 15 30 44

### CODE REVIEW

**Comment by katarinabatina** [comment]
image

**Comment by mennenia** [comment]
@katarinabatina updated!

@sarahscott the magical code added property was `space-around` on `justifyContent` rather than `flex-start`

screen shot 2016-05-31 at 17 10 38

**Comment by katarinabatina** [comment]
@mennenia 💯  magic! 👏

**Comment by alloy** [comment]
Awesome, well done 👍

**Comment by sarahscott** [comment]
@mennenia The only problem here is that the last item might be centered instead of aligned left - do you have any screenshots with the last row when there's an item on its own?

**Comment by sarahscott** [comment]
See #101

**Comment by sarahscott** [comment]
I don't know if this is relevant for us but someone else suggests using a spacer: http://stackoverflow.com/questions/18744164/flex-box-align-last-row-to-grid

**Comment by alloy** [comment]
@sarahscott Ah, so this is basically what you had previously? If all else fails in a timely manner (we need to release this week) then I'm not at all opposed to adding a dummy element.

File: lib/components/artist/related_artists/index.js [hunk 1]
```diff
@@ -3,25 +3,36 @@
...
         <View style={styles.artistContainer}>
-          { artists.map(artist => <RelatedArtist key={artist.id} artist={artist} /> ) }
+          { this.renderArtists() }
         </View>
       </View>
     );
   }
+
+  renderArtists() {
+    const artists = this.props.artists;
```
Comment (sarahscott) [inline lib/components/artist/related_artists/index.js]: @mennenia this is just an illustrative commit to show the spacer idea - how do you feel about this? It fixes the issue for iPhone: 
simulator screen shot may 31 2016 5 23 13 pm

but not for iPad, so we'll have to do something else for that:

simulator screen shot may 31 2016 5 24 59 pm

**Comment by mennenia** [comment]
Current situation:

ipad

simulator screen shot 1 jun 2016 18 35 58

File: lib/components/artist/related_artists/index.js [hunk 2]
```diff
@@ -3,35 +3,67 @@
...
 class RelatedArtists extends React.Component {
+    constructor(props) {
+    super(props);
+    this.state = { columns: this.columnCount()};
+    this.onLayout = this.onLayout.bind(this);
+  }
+  
+  columnCount() {
+    const isPhone = Dimensions.get('window').width < 700;
+    const isPadHorizontal = Dimensions.get('window').width > 1000;
```
Comment (alloy) [inline lib/components/artist/related_artists/index.js]: Maybe reduce method calls a bit more by storing the `window` object?

(Not sure about this case, but might be relevant in cases where behind the scenes it calls a native module and it needs to go over the bridge back and forth multiple times.)

File: lib/components/artist/related_artists/index.js [hunk 3]
```diff
@@ -3,35 +3,67 @@
...
+    return !isPhone ? isPadHorizontal ? 4 : 3 : 2;
```
Comment (alloy) [inline lib/components/artist/related_artists/index.js]: Can you add parentheses around the nested ternary?

**Comment by sarahscott** [comment]
rebase reminder 😁

**Comment by katarinabatina** [comment]
@mennenia magical magic of magicness 👏 👏 👏 👏  kudos!

**Comment by mennenia** [comment]
Cheers @katarinabatina ^_^ this was proper team effort from @sarahscott and @alloy also :D.

@sarahscott - comments addressed, master merged. Good to go on my end :)!

**Comment by sarahscott** [comment]
merging!

File: lib/components/artist/related_artists/index.js [hunk 4]
```diff
@@ -10,6 +10,8 @@ import SerifText from '../../text/serif';
 import ImageView from '../../opaque_image_view';
 import RelatedArtist from './related_artist'
 
+const window = Dimensions.get('window')
```
Comment (alloy) [inline lib/components/artist/related_artists/index.js]: Interesting, so the `width` value still updates after orientation changes?

I actually meant to do it once inside the `columnCount` method, but if this works that’s even better and we can do this in other places too.

Comment (mennenia) [inline lib/components/artist/related_artists/index.js]: yeah we tested it and it worked, so, yay! :)

File: lib/components/artist/related_artists/index.js [hunk 5]
```diff
@@ -18,23 +20,21 @@ class RelatedArtists extends React.Component {
   }
   
   columnCount() {
-    const isPhone = Dimensions.get('window').width < 700;
-    const isPadHorizontal = Dimensions.get('window').width > 1000;
-    return !isPhone ? isPadHorizontal ? 4 : 3 : 2;
+    const isPhone = window.width < 700;
+    const isPadHorizontal = window.width > 1000;
+    return !isPhone ? (isPadHorizontal ? 4 : 3) : 2;
```
Comment (alloy) [inline lib/components/artist/related_artists/index.js]: In the future it’s better to reduce the amount of negation, as it will be more readable.

File: lib/components/artist/related_artists/index.js (hunk 4 above)
Comment (alloy) [inline lib/components/artist/related_artists/index.js]: Noice! I wonder how that works under the hood, will have to look into that some time.
