### PR TITLE
[Inbox] Active Bids fixes

### LINKED ISSUE #662: [MSG] Active Bids aren’t tappable
They should probably take you to the artwork view.

### LINKED ISSUE #663: [MSG] Active Bids doesn’t reload
After bidding on a work and pull to refresh the bid is not shown. Only restarting the app works.

### PR DESCRIPTION
**Pull request by alloy**
Fixes #662 
Fixes #663

Also makes it so the `Inbox` always force fetches data on load so that the `ZeroInboxState` hides when bids/conversations exist.

Will comment inline.

Skip New Tests.

### CODE REVIEW

File: src/lib/Components/Inbox/Bids/ActiveBid.tsx [hunk 1]
```diff
@@ -134,32 +134,13 @@ export default Relay.createContainer(ActiveBid, {
...
-              is_live_open
-              is_closed
-            }
-            highest_bid {
-              cents
-              display
-            }
             artwork {
-              id
-              title
```
Comment (alloy) [inline src/lib/Components/Inbox/Bids/ActiveBid.tsx]: This component was massively over-fetching data. Is that because of a certain workflow you using while building out these components? Are there other places we should check to ensure we don’t over-fetch?

**Comment by ArtsyOpenSource** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>

  Missing Test Files:

- `src/lib/Components/Inbox/Bids/__tests__/index-tests.tsx`
- `src/lib/Components/Inbox/Conversations/__tests__/index-tests.tsx`

If these files are supposed to not exist, please update your PR body to include "Skip New Tests".
  </td>
    </tr>
  </tbody>
</table>




<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

File: src/lib/Containers/Inbox.tsx [hunk 2]
```diff
@@ -2,51 +2,79 @@ import * as React from "react"
...
+      : <ZeroStateInbox />
   }
 }
 
+// FIXME The `lot_standings` snippet is copy-pasted from the `ActiveBids` component so it doesn’t fetch data that’s not
+//       really needed, MP should really just expose something like `has_active_bids` and ensure that it doesn’t perform
+//       extra backend reuqests to determine if it has active bids and resolve the `ActiveBids` query.
+//
+//       The same applies to the `conversations` snippet.
+//
```
Comment (alloy) [inline src/lib/Containers/Inbox.tsx]: See TODO.

File: src/lib/Components/Inbox/Bids/ActiveBid.tsx (hunk 1 above)
Comment (l2succes) [inline src/lib/Components/Inbox/Bids/ActiveBid.tsx]: In this particular case, it was in part because the dev process involved a lot of trial and error to figure out where the display data came from. 

Also, since there are still some unknowns about active bids, namely where rows should be routing to (artwork view, auction page, etc...), we decided to hold on for that because the auctions team was changing auction urls. The plan was to update the fragment after we figure the new URI format. Anyway, sorry I should've left a comment explaining that.

File: src/lib/Components/Inbox/Bids/ActiveBid.tsx [hunk 3]
```diff
@@ -95,6 +99,10 @@ class ActiveBid extends React.Component<RelayProps, State> {
     }
   }
 
+  handleTap() {
+    SwitchBoard.presentNavigationViewController(this, this.props.bid.active_bid.sale_artwork.artwork.href)
```
Comment (l2succes) [inline src/lib/Components/Inbox/Bids/ActiveBid.tsx]: I recall talking about routing to an auction lot VC for the bid in question but we can update that once we have the URI

**Comment by l2succes** [comment]
I actually had it implemented that exact same way before but I changed it because pagination was broken on the Messages section for some reason. I'll just double-check it still works before merging.

File: src/lib/Components/Inbox/Bids/ActiveBid.tsx (hunk 1 above)
Comment (alloy) [inline src/lib/Components/Inbox/Bids/ActiveBid.tsx]: Alrighty. So this isn’t an issue elsewhere?

Comment (l2succes) [inline src/lib/Components/Inbox/Bids/ActiveBid.tsx]: Not that I know of, I think it's an isolated case but we can always check other relay containers in the app to make sure we're not over-fetching data.

**Comment by l2succes** [comment]
Ok, I tested the code on device, pagination still works and new data get loaded on pull-to-refresh so we're good. Merging
